export const locales = {
  he: {
    dir: "rtl", brand: "ארצי אנרגיה", line: "אנרגיה חכמה. מבט רחוק.", skip: "דלג לתוכן",
    nav: ["בית", "אודות", "פתרונות", "טכנולוגיות", "מגזין", "יצירת קשר"],
    hero: ["לא מחכים", "לזריחה.", "יוצרים אותה."],
    heroDesc: "יש גגות שרואים בהם שטח פנוי. אנחנו רואים בהם אפשרות. חשיבה סולארית שמשלבת הנדסה, אדריכלות וראייה לטווח ארוך.",
    contact: "בואו נדבר", discover: "לגלות עוד", view: "לכל הפתרונות", scroll: "גללו אל העתיד",
    vision: ["מעל לכל גג.", "יש עתיד."], visionDesc: "התאמה נכונה מתחילה בהקשבה למבנה, לצרכים ולאנשים. כל תכנון דורש בירור מדויק של התנאים והאפשרויות.",
    solutions: ["גג אחד.", "אפשרויות רבות."], solDesc: "ארבעה עולמות של חשיבה סולארית. כל פתרון מצריך בדיקת היתכנות ותכנון מקצועי.",
    technology: ["כל פרט קטן.", "שינוי גדול."], techDesc: "מודולים, ממירים, ניטור, אגירה והנדסת מבנים — מרכיבים שמתחברים לתמונה הנדסית אחת.",
    projectTitle: ["המרחב משתנה.", "האפשרות נשארת."], projectDesc: "תרחישים להמחשה בלבד. אין כאן טענה לפרויקטים שבוצעו על ידי ארצי אנרגיה.",
    gallery: ["אור. חומר.", "אפשרות."], galleryDesc: "תצלומי השראה להמחשה בלבד, ולא תיק עבודות מאומת של החברה.",
    processTitle: ["מכירים לעומק.", "מתכננים קדימה."], processDesc: "מהבנה ראשונית של הגג ועד תכנון, הקמה ותחזוקה בהתאם לתנאים ולאישורים.",
    labTitle: ["הגג שלכם.", "המספרים שלו."], labDesc: "הדמיה חישובית ראשונית בלבד, עם הנחות גלויות וללא התחייבות.",
    compTitle: ["משווים אפשרויות.", "לא מנחשים."], compDesc: "השוואה כללית בין סוגי מרחבים, לא המלצה הנדסית פרטנית.",
    journalTitle: ["ידע הוא", "אנרגיה."], journalDesc: "מידע שימושי ומדריכים על הדרך שבה מתכננים, מפעילים ומתחזקים מערכות סולאריות.",
    guidesTitle: ["הדרך מתחילה", "בשאלות הנכונות."], guidesDesc: "מדריכים מעשיים למי שבוחנים פתרון סולארי.",
    faqTitle: ["שאלות טובות.", "פתיחה נכונה."], faqDesc: "תשובות ראשוניות — תמיד נדרשת בדיקה מותאמת למבנה.",
    contactTitle: ["הדבר הבא", "מתחיל בשיחה."], contactDesc: "ספרו לנו על הנכס ועל המטרות, ונוכל להתחיל לבחון את האפשרויות.",
    quoteTitle: ["מתחילים נכון.", "צעד אחר צעד."], quoteDesc: "טופס בקשה בשלבים. זו אינה הצעת מחיר מחייבת.",
    privacyTitle: ["פרטיות היא", "חלק מהתכנון."], accessTitle: ["חוויה שנועדה", "לכולם."], termsTitle: ["התמונה המלאה.", "גם בפרטים."],
    subtitle: "תכנון אחראי מתחיל בנתונים אמיתיים", numbers: "מספרים להמחשה", projectLabel: "תרחיש לדוגמה", articleLabel: "ידע / מגזין",
    search: "חיפוש מאמר", filter: "סינון", all: "כל הקטגוריות", noResults: "לא נמצאו תוצאות.",
    read: "לקריאה", back: "חזרה למגזין", related: "אולי יעניין אתכם", guided: "לכל המדריכים", next: "המשך", previous: "חזרה",
    submit: "שליחת פנייה", submitted: "הפנייה נקלטה בהצלחה.", submitError: "השליחה לא הצליחה. אפשר לפנות אלינו בוואטסאפ.",
    inputError: "יש להזין שם מלא, דוא״ל תקין ולאשר את השימוש בפרטים.", sending: "שולח...",
    fullName: "שם מלא", email: "כתובת דוא״ל", phone: "טלפון", property: "סוג הנכס", message: "ספרו לנו על הפרויקט",
    consent: "קראתי את הודעת הפרטיות ואני מאשר/ת שמירת פרטי הפנייה לצורך יצירת קשר.",
    disclosure: "מסירת הפרטים היא מרצון. המידע יישמר ב־Supabase לצורך טיפול בפנייה. אין להזין מידע רגיש.",
    whatsapp: "דברו בוואטסאפ", waText: "שלום ארצי אנרגיה, הגעתי מהאתר ואשמח לדבר על פתרון סולארי.",
    area: "שטח גג פנוי", exposure: "חשיפה לשמש", good: "טובה", medium: "בינונית", capacity: "הספק מותקן משוער",
    yearly: "ייצור שנתי משוער", labDisclaimer: "להמחשה בלבד: 0.17 קילוואט לכל מ״ר × 1,500 קוט״ש לקילוואט בשנה × מקדם חשיפה (1 או 0.72). לא תחזית, ייעוץ הנדסי או הצעת מחיר.",
    install: "התקנת אפליקציה", themeNotice: "האתר שומר העדפת שפה מקומית בלבד, ללא עוגיות פרסום.",
    ack: "הבנתי", preview: "גרסת Preview: תמונות להמחשה; לא תיק פרויקטים מאומת או התחייבות מקצועית.",
    categories: ["תכנון", "טכנולוגיה", "תחזוקה", "תפעול", "קיימות"],
    services: [
      ["residential", "גגות פרטיים", "המהפכה מתחילה בבית.", "תכנון המתחשב במבנה הבית, בתנאי הגג, במערכת החשמל ובצריכה."],
      ["commercial", "מבני מסחר ותעשייה", "תנו לגג לעבוד חכם.", "פתרון תכנוני שצריך להתחשב בעומסים, תפעול ובציוד קיים."],
      ["agriculture", "מבנים חקלאיים", "פוטנציאל שצומח מהשטח.", "התאמה לסביבה חקלאית, לתשתיות ולאופי הפעילות."],
      ["operations", "ניטור, תחזוקה ושדרוג", "לראות יותר מהקיים.", "בחינת נתוני הפקה, מצב ציוד ואפשרויות תחזוקה ושיפור."]
    ],
    systems: [
      ["modules", "מודולים סולאריים", "המרת קרינת שמש לאנרגיה חשמלית בתנאים משתנים."],
      ["inverters", "ממירים", "בחירת ציוד הממיר ומבקר את זרימת החשמל."],
      ["monitoring", "ניטור ביצועים", "הבנת נתוני מערכת וזיהוי שינויים לאורך זמן."],
      ["storage", "אגירת אנרגיה", "אפשרות שדורשת אפיון צורך, בטיחות ורגולציה."],
      ["engineering", "הנדסת גגות", "תכנון עומסים, הצללות, גישה בטוחה ותשתיות."]
    ],
    steps: [["01", "היכרות", "מבינים את הנכס, הצרכים והמגבלות."], ["02", "בדיקת היתכנות", "בוחנים צל, עומסים, תשתיות ואישורים."], ["03", "תכנון והקמה", "מגבשים תוכנית ופועלים לפי אישורים מקצועיים."], ["04", "ניטור וליווי", "חושבים גם על ביצועים ותחזוקה לטווח הארוך."]],
    faq: [
      ["האם כל גג מתאים למערכת סולארית?", "לא בהכרח. יש לבחון הצללה, מצב הגג, עומסים, שטח פנוי, תשתיות ואישורים."],
      ["כמה אנרגיה מערכת יכולה לייצר?", "הייצור משתנה לפי מיקום, מזג אוויר, הספק, כיוון, צל ונצילות הציוד. נדרשת תחזית מקצועית."],
      ["האם המחשבון באתר מדויק?", "הוא נועד להמחשת סדרי גודל ולא להחלטות מקצועיות או כלכליות."],
      ["מה חשוב לבחון לפני הצעת מחיר?", "כדאי להבין מה נמדד, מה הוערך, אילו רכיבים נכללים ומה התנאים והאחריות."],
      ["מי רשאי לטפל ברכיבי חשמל?", "רק אנשי מקצוע בעלי הסמכות המתאימות; אין לגעת במערכת חשמל פעילה."],
      ["מהי תחזוקה שוטפת?", "ניטור, תיעוד ובדיקות לפי הוראות היצרן, האתר וגורמי המקצוע."],
      ["אפשר לשדרג מערכת קיימת?", "לעיתים, לאחר בדיקת התאמה, בטיחות, מצב הציוד ועלויות."],
      ["איך מתחילים?", "פונים עם מידע בסיסי על הנכס כדי לקבוע אילו בדיקות נדרשות."]
    ]
  },
  en: {
    dir: "ltr", brand: "ARTZI ENERGY", line: "Smarter energy. A wider perspective.", skip: "Skip to content",
    nav: ["Home", "About", "Solutions", "Technology", "Journal", "Contact"],
    hero: ["Don't wait", "for the sunrise.", "Create it."],
    heroDesc: "Some see unused rooftop space. We see potential. Solar thinking that brings engineering, architecture and long-term vision together.",
    contact: "Let's talk", discover: "Discover more", view: "Explore solutions", scroll: "Scroll into the future",
    vision: ["The future starts", "above us."], visionDesc: "A good solution begins with understanding the building, people and needs. Every design requires a careful look at conditions and possibilities.",
    solutions: ["One rooftop.", "Many possibilities."], solDesc: "Four approaches to solar thinking. Each calls for its own feasibility assessment and professional design.",
    technology: ["Every little detail.", "A big difference."], techDesc: "Modules, inverters, monitoring, storage and structural engineering make up a connected design process.",
    projectTitle: ["Different spaces.", "Endless potential."], projectDesc: "Illustrative use cases only. They do not represent verified Artzi Energy projects.",
    gallery: ["Light. Form.", "Possibility."], galleryDesc: "Illustrative inspiration photography, not a verified portfolio of the company's work.",
    processTitle: ["Understand first.", "Design forward."], processDesc: "From rooftop assessment to professional design, installation and ongoing consideration.",
    labTitle: ["Your rooftop.", "The numbers behind it."], labDesc: "A simple simulation with transparent assumptions, not a binding estimate.",
    compTitle: ["Compare concepts.", "Avoid guesswork."], compDesc: "A general comparison of site types, not project-specific engineering advice.",
    journalTitle: ["Knowledge", "is energy."], journalDesc: "Useful ideas and guides for planning, operating and caring for solar systems.",
    guidesTitle: ["It starts", "with better questions."], guidesDesc: "Practical guides for people exploring a solar installation.",
    faqTitle: ["Good questions.", "Great beginnings."], faqDesc: "Starting points only — a site-specific assessment remains essential.",
    contactTitle: ["Your next idea", "starts here."], contactDesc: "Tell us about your property and your goals so we can start exploring options.",
    quoteTitle: ["Start right.", "Step by step."], quoteDesc: "A multistep inquiry, not a binding quotation.",
    privacyTitle: ["Privacy is", "part of the plan."], accessTitle: ["An experience", "for everyone."], termsTitle: ["The whole story.", "Including the details."],
    subtitle: "Responsible design begins with real data", numbers: "Illustrative figures", projectLabel: "Concept scenario", articleLabel: "Knowledge / journal",
    search: "Search articles", filter: "Filter", all: "All categories", noResults: "No matching results.",
    read: "Read article", back: "Back to journal", related: "You might also like", guided: "All guides", next: "Next", previous: "Back",
    submit: "Send inquiry", submitted: "Your inquiry was received.", submitError: "Submission failed. Please contact us on WhatsApp.",
    inputError: "Enter a valid full name, email and privacy consent.", sending: "Sending...",
    fullName: "Full name", email: "Email", phone: "Phone", property: "Property type", message: "Tell us about your project",
    consent: "I have read the privacy notice and agree to the storage of my inquiry details for a response.",
    disclosure: "Providing details is voluntary. Information is stored in Supabase solely to respond. Do not submit sensitive information.",
    whatsapp: "Chat on WhatsApp", waText: "Hello Artzi Energy, I found you online and would love to discuss a solar solution.",
    area: "Available roof area", exposure: "Sun exposure", good: "Good", medium: "Moderate", capacity: "Indicative installed capacity",
    yearly: "Indicative yearly generation", labDisclaimer: "Illustration only: 0.17 kW per m² × 1,500 kWh per installed kW annually × exposure factor (1 or 0.72). Not a forecast, engineering advice or a price quote.",
    install: "Install app", themeNotice: "The site stores local language preference only; no advertising cookies.",
    ack: "Got it", preview: "Preview website: illustrative photography, not verified past projects or professional guarantees.",
    categories: ["Planning", "Technology", "Maintenance", "Operations", "Sustainability"],
    services: [
      ["residential", "Residential rooftops", "Change starts at home.", "Planning around the home, roof conditions, electrical installation and consumption."],
      ["commercial", "Commercial & industrial", "Put the roof to work.", "Design that considers structural loads, operations and existing rooftop equipment."],
      ["agriculture", "Agricultural buildings", "Opportunity grows here.", "A response to agricultural environments, infrastructure and site operations."],
      ["operations", "Monitoring, care & upgrades", "A new view of the existing.", "Reviewing output, equipment condition and possible maintenance or improvements."]
    ],
    systems: [
      ["modules", "Photovoltaic modules", "Converting sunlight into electrical power under changing conditions."],
      ["inverters", "Inverters", "Equipment that converts and manages electrical power."],
      ["monitoring", "Performance monitoring", "Understanding output data and spotting changes over time."],
      ["storage", "Energy storage", "An option that requires safety, purpose and regulatory assessments."],
      ["engineering", "Rooftop engineering", "Loads, shade, safe access and building infrastructure."]
    ],
    steps: [["01", "Discover", "Understand the property, needs and limitations."], ["02", "Assess feasibility", "Review shade, structure, infrastructure and approvals."], ["03", "Design and build", "Develop a plan and follow professional approvals."], ["04", "Monitor and care", "Look ahead to performance and long-term maintenance."]],
    faq: [
      ["Is every rooftop suitable for solar?", "Not necessarily. Shading, structure, usable area, electrical infrastructure and approvals matter."],
      ["How much energy can a system produce?", "It varies with location, weather, capacity, direction, shading and equipment. Professional estimates are needed."],
      ["Is this site's calculator accurate?", "It illustrates rough magnitude, not project-specific or financial decisions."],
      ["What should I review before a quote?", "Find out what was measured versus estimated, which components are included, and service and warranty terms."],
      ["Who may work on electrical components?", "Only qualified professionals; never handle energized electrical equipment."],
      ["What does maintenance involve?", "Monitoring, records and checks according to equipment and professional guidance."],
      ["Can an existing system be upgraded?", "Sometimes, subject to technical, safety and economic assessment."],
      ["How do I begin?", "Share basic property details to determine which assessments are needed."]
    ]
  }
};
export const photos = [
  "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1800&q=78",
  "https://images.unsplash.com/photo-1624397640148-949b1732bb0a?auto=format&fit=crop&w=1350&q=78",
  "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=1350&q=78",
  "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1350&q=78",
  "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=1350&q=78",
  "https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?auto=format&fit=crop&w=1350&q=78"
];
export const articleSpecs = [
  ["roof-readiness",0,"האם הגג מתאים לסולארי?","Is your roof solar-ready?","מצב גג, איטום ועומסים","Roof structure and waterproofing","שטח פנוי והצללות","Usable area and shading","אישורים ותשתיות חשמל","Permissions and electrical infrastructure"],
  ["shading",0,"הצללות והשפעתן על תפוקה","How shade affects solar output","הצל נע במהלך היום","Shadows move across the day","ציוד, עצים ומעקות","Equipment, trees and railings","ניתוח עונתי מקצועי","Professional seasonal analysis"],
  ["module-choice",1,"בחירת מודולים פוטו־וולטאיים","Choosing photovoltaic modules","מפרט ונצילות","Specifications and efficiency","טמפרטורה ותנאי שטח","Temperature and site conditions","מסמכי אחריות ואיכות","Warranty and quality documents"],
  ["inverters",1,"ממירים סולאריים – מדריך","Understanding solar inverters","זרם ישר וזרם חילופין","Direct and alternating current","התאמה למתח ולהספק","Voltage and capacity matching","הגנות וניטור","Protection and monitoring"],
  ["monitoring",2,"למה כדאי לנטר מערכת?","Why monitor solar performance?","נתוני ייצור ושינויים","Production data and changes","השוואה למזג אוויר","Weather context","פעולות המשך מקצועיות","Professional follow-up"],
  ["maintenance",2,"עקרונות תחזוקת מערכת","Solar maintenance essentials","ניטור תקופתי","Periodic monitoring","גישה בטוחה לגג","Safe roof access","הוראות יצרן ומסמכים","Manufacturer guidance"],
  ["commercial-roofs",3,"גגות מסחריים ותעשייתיים","Commercial and industrial rooftops","פעילות עסקית רציפה","Operational continuity","עומסים ומערכות קיימות","Loads and existing equipment","תיאום עבודות והיתרים","Coordination and permits"],
  ["agricultural-sites",3,"מערכות סולאריות בחקלאות","Solar on agricultural buildings","לחות, אבק וסביבה","Dust, humidity and environment","צרכים תפעוליים","Operational needs","התאמה למבנה","Structural suitability"],
  ["storage",1,"אגירת אנרגיה: מה בודקים?","Energy storage: what to assess","הגדרת המטרה","Defining the purpose","בחירת קיבולת","Selecting capacity","מיקום, בטיחות ותקינה","Location, safety and standards"],
  ["feasibility",0,"איך בוחנים כדאיות?","Evaluating solar feasibility","נתוני צריכה אמיתיים","Real electricity usage","הנחות תפוקה ועלויות","Generation and cost assumptions","ניתוח אי־ודאות","Uncertainty and scenarios"],
  ["panel-tilt",0,"כיוון ושיפוע המודולים","Solar panel direction and tilt","זווית השמש","Sun angles","רוח ומגבלות מבניות","Wind and structural limits","גישה ותחזוקה","Access and maintenance"],
  ["roof-safety",3,"בטיחות בעבודה על גגות","Safety on solar rooftops","עבודה בגובה","Working at height","בטיחות חשמל","Electrical safety","תכנון נתיבי גישה","Access route design"],
  ["grid-connection",3,"חיבור מערכת לרשת","Connecting a solar system","בדיקת תשתית קיימת","Existing infrastructure","דרישות ואישורים","Approvals and requirements","בדיקות חיבור","Connection inspections"],
  ["seasonal-output",0,"מדוע התפוקה משתנה בעונות?","Why output changes by season","אורך יום וקרינה","Day length and irradiation","עננות וחום","Clouds and temperature","מבט שנתי על נתונים","Year-round data"],
  ["solar-warranties",2,"אחריות של ציוד ועבודה","Solar equipment and work warranties","מה כוללת אחריות יצרן","Manufacturer warranties","אחריות התקנה","Installation terms","שמירת תיעוד","Keeping system records"],
  ["solar-architecture",4,"אנרגיה ואדריכלות","Solar thinking in architecture","שילוב עם מעטפת המבנה","Integrating the building envelope","גגות שימושיים","Multipurpose rooftops","תכנון בין־תחומי","Cross-disciplinary design"],
  ["performance-review",2,"בדיקת מערכת קיימת","Reviewing an existing solar system","מדידת ביצועים","Reading performance","הצללה חדשה ובלאי","New shade and wear","החלטה על טיפול","Choosing appropriate service"],
  ["weather-effects",0,"מזג אוויר והשפעתו על ייצור","Weather and solar generation","קרינה ועננות","Sunlight and clouds","השפעת הטמפרטורה","Temperature effects","נתוני מזג אוויר לאורך זמן","Long-term climate data"],
  ["solar-myths",4,"מיתוסים על אנרגיה סולארית","Common solar energy myths","לא כל גג מתאים","Not every roof fits","אין תפוקה אוניברסלית","No universal yield","הבטחות מול נתונים","Evidence instead of promises"],
  ["future-of-solar",4,"העתיד של אנרגיה על גגות","The future of rooftop energy","ניטור ומידע","Monitoring and data","אגירה ומערכות חכמות","Storage and smart systems","חשיבה על התאמה","Site fit comes first"]
];
export const guideSpecs = [
  ["start", "תחילת הדרך למערכת סולארית", "Starting a solar project", "אוספים נתוני נכס", "Collect property data", "בוחנים תשתיות", "Review infrastructure", "קובעים בדיקה מקצועית", "Arrange a professional review"],
  ["quote", "מה לשאול לפני הצעת מחיר?", "Questions before requesting a quote", "מה נבדק פיזית?", "What was verified?", "איזה ציוד כלול?", "Which components are included?", "מה תנאי האחריות?", "What are the warranty terms?"],
  ["site-visit", "הכנה לבדיקת גג", "Preparing for a roof assessment", "ממפים גג וציוד", "Map roof and equipment", "מאתרים מוקדי צל", "Identify shade sources", "בודקים גישה בטוחה", "Check safe access"],
  ["monitoring", "איך קוראים נתוני ניטור?", "Reading monitoring data", "מזהים את המדדים", "Identify system metrics", "משווים נתוני עונות", "Compare seasons", "מתעדים חריגות", "Document anomalies"],
  ["maintenance", "בניית שגרת תחזוקה", "Building a maintenance routine", "שומרים הוראות יצרן", "Keep manufacturer guidance", "מגדירים בעלי אחריות", "Define responsible people", "מזמינים בדיקות מוסמכות", "Schedule qualified checks"],
  ["commercial", "הכנת מבנה תעשייתי", "Preparing an industrial building", "ממפים תשתיות פעילות", "Map active infrastructure", "מתאמים עם צוות תפעול", "Coordinate with operations", "בוחנים בטיחות", "Review site safety"],
  ["handover", "רשימת בדיקה למסירת מערכת", "Solar system handover checklist", "מקבלים מפרטים", "Collect specifications", "מבקשים מסמכי אחריות", "Collect warranties", "לומדים לפתוח קריאת שירות", "Understand service requests"],
  ["shading", "בדיקת הצללות ראשונית", "A first look at shading", "מאתרים מקורות צל", "Locate shade sources", "בודקים שעות ועונות", "Consider time and season", "מעבירים לבדיקה הנדסית", "Get engineering assessment"]
];
